// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0Dxf7QHgjhxDb5KtUZ8HlL_eYFkPWt68',
    appId: '1:830085513783:web:8c894813909964134eb5b2',
    messagingSenderId: '830085513783',
    projectId: 'chat-app-571e6',
    authDomain: 'chat-app-571e6.firebaseapp.com',
    storageBucket: 'chat-app-571e6.firebasestorage.app',
    measurementId: 'G-DY0LGNHJGF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlYu2LhDaO7-15hhTSo_lFFpe60zS2RQ8',
    appId: '1:830085513783:android:729c90b46347df1e4eb5b2',
    messagingSenderId: '830085513783',
    projectId: 'chat-app-571e6',
    storageBucket: 'chat-app-571e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRPTPOyjyHrGHzKWs3y5dcbkk5F6C-ylE',
    appId: '1:830085513783:ios:a26025729fe0f80d4eb5b2',
    messagingSenderId: '830085513783',
    projectId: 'chat-app-571e6',
    storageBucket: 'chat-app-571e6.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRPTPOyjyHrGHzKWs3y5dcbkk5F6C-ylE',
    appId: '1:830085513783:ios:a26025729fe0f80d4eb5b2',
    messagingSenderId: '830085513783',
    projectId: 'chat-app-571e6',
    storageBucket: 'chat-app-571e6.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0Dxf7QHgjhxDb5KtUZ8HlL_eYFkPWt68',
    appId: '1:830085513783:web:19f1613a1a77c9064eb5b2',
    messagingSenderId: '830085513783',
    projectId: 'chat-app-571e6',
    authDomain: 'chat-app-571e6.firebaseapp.com',
    storageBucket: 'chat-app-571e6.firebasestorage.app',
    measurementId: 'G-LWEX3XPWJJ',
  );
}
